2025-PinTech-Hackathon/Team8-BE

src/main/auth/middlewares.py
- #1 
- 내부적으로 요청한 사용자에 대한 ID를 필요로 할 때 손쉽게 조회하기 위한, 미들웨어 함수 작성
=> [Feat] (Internal) 사용자 ID 조회

src/main/domain/database.py, src/main/domain/dto/InformationResponseDto.py, src/main/domain/model/Challenge.py, src/main/domain/model/ChallengeRoom.py, src/main/domain/model/ChallengeStatusEnum.py, src/main/domain/model/Check.py, src/main/domain/model/Code.py, src/main/domain/model/Information.py, src/main/domain/model/Member.py, src/main/domain/model/MemberChallengeRoom.py, src/main/domain/model/MemberEnum.py, src/main/repository/mainRepository.py, src/main/router/MainAPIRouter.py, src/main/service/mainService.py
- 도메인 설정
- 도메인 간 연관관계도 설정
- 데이터베이스 설정
=> Feat: 도메인 설정

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/domain/database.py
=> Refactor: 환경변수 수정

src/main/domain/database.py
=> [Fix] DB URL 구조 수정

src/app.py
=> [Feat] Swagger 테스트 가능하도록 수정

src/main/repository/MainRepository.py, src/main/router/MainAPIRouter.py, src/main/service/MainService.py
=> [Feat] 사용자 태그 목록 조회

src/app.py, src/main/domain/models.py, src/main/repository/InformationRepository.py, src/main/router/FeedAPIRouter.py, src/main/service/FeedService.py, src/router.py
=> [Feat] 일반 금융 상세 페이지

src/main/router/ChallengeAPIRouter.py, src/main/service/ChallengeService.py, src/router.py
=> [Feat] 챌린지 소개 페이지

src/main/domain/dto/ProfileInputDto.py, src/main/repository/MemberRepository.py, src/main/router/ProfileAPIRouter.py, src/main/service/ProfileService.py, src/router.py
=> [Feat] 사용자 정보 입력

src/main/domain/dto/ProfileInputDto.py, src/main/domain/dto/ProfileOutputDto.py, src/main/domain/model/MemberEnum.py, src/main/router/ProfileAPIRouter.py, src/main/service/ProfileService.py
=> [Feat] 프로필 모달 화면

src/main/service/MainService.py
=> Feat/9 맞춤형 챌린지 메인 페이지 구현

src/main/domain/dto/MyChallengeDto.py, src/main/repository/ChallengeRepository.py, src/main/repository/ChallengeRoomRepository.py, src/main/router/MyChallengeRouter.py, src/main/service/_MyChallengeService.py
=> [Feat] 내 챌린지 보여주기

src/main/repository/MemberRepository.py
=> [Hotfix] 프로필 추가 시 정상 응답 처리

src/main/router/FeedAPIRouter.py
=> [Feat] 일반 금융 상세 페이지 내 redirectUrl 추가 

src/main/domain/dto/MyChallengeDto.py, src/main/repository/ChallengeRoomRepository.py, src/main/router/MyChallengeRouter.py, src/main/service/_MyChallengeService.py
=> Feat/33 친구 초대하기 모달 페이지 구현

src/main/domain/dto/MyChallengeDto.py, src/main/repository/CheckRepository.py, src/main/router/MyChallengeRouter.py, src/main/service/_MyChallengeService.py
=> [Feat] 함께 하는 친구 진행율

src/main/domain/dto/MyChallengeDto.py, src/main/router/MyChallengeRouter.py, src/main/service/_MyChallengeService.py
=> Feat: 초대 코드로 챌린지 참여

src/main/domain/dto/MyChallengeDto.py, src/main/repository/CheckRepository.py, src/main/router/MyChallengeRouter.py, src/main/service/_MyChallengeService.py
=> [Feat] 챌린지 달력

src/main/router/MyChallengeListRouter.py, src/main/service/_MyChallengeListService.py
=> [Refactor] service 로직 고치기 완료

src/main/service/_MyChallengeService.py
=> [Fix] friend 오류 고치기
